development:
  adapter: mysql2
  encoding: utf8
  database: keywords_development
  pool: 5
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  database: keywords_test
  pool: 5
  username: root
  password: root